package ui

import _ "embed"

// Tray icon resource data (raw BMP: BITMAPINFOHEADER + XOR + AND mask).
// Generated by gen_icons.py — status-colored rounded badge with a white hexagon.
// Consumed directly by CreateIconFromResourceEx (no offset needed).

//go:embed green.bin
var greenIconBytes []byte

//go:embed yellow.bin
var yellowIconBytes []byte

//go:embed red.bin
var redIconBytes []byte

// blueIconBytes returns a simple blue circle icon resource (fallback, generated in code).
func blueIconBytes() []byte { return genCircleIconBytes(0x26, 0x4F, 0x78) }

// genCircleIconBytes generates raw BMP resource data for a 16x16 filled-circle icon.
// Used only for the blue fallback icon.
func genCircleIconBytes(r, g, b byte) []byte {
	const w, h = 16, 16
	le16 := func(b []byte, v uint16) { b[0], b[1] = byte(v), byte(v>>8) }
	le32 := func(b []byte, v uint32) { b[0], b[1], b[2], b[3] = byte(v), byte(v>>8), byte(v>>16), byte(v>>24) }

	// XOR mask (BGRA, bottom-up)
	xor := make([]byte, w*h*4)

	// AND mask: 1bpp, row-aligned to 4 bytes, bottom-up
	rowBytes := ((w + 31) / 32) * 4
	and := make([]byte, rowBytes*h)
	for i := range and {
		and[i] = 0xFF // all transparent by default
	}

	for y := 0; y < h; y++ {
		by := h - 1 - y // bottom-up
		xorRow := by * w * 4
		andRow := y * rowBytes
		for x := 0; x < w; x++ {
			dx, dy := float64(x-8), float64(y-8)
			if dx*dx+dy*dy <= 49 {
				o := xorRow + x*4
				xor[o], xor[o+1], xor[o+2], xor[o+3] = b, g, r, 0xFF
				// clear AND bit → opaque
				and[andRow+x/8] &^= 1 << (7 - uint(x%8))
			}
		}
	}

	bh := make([]byte, 40)
	le32(bh, 40)
	le32(bh[4:], uint32(w))
	le32(bh[8:], uint32(h*2))
	le16(bh[12:], 1)
	le16(bh[14:], 32)

	bmp := make([]byte, 0, 40+len(xor)+len(and))
	bmp = append(bmp, bh...)
	bmp = append(bmp, xor...)
	bmp = append(bmp, and...)
	return bmp
}
